#page title
page_title: Wealth Wise # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1532754684 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Wealth Wise # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: £2.99 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Get control over your finances with Wealth Wise. A simple Net Worth Tracking app giving you full control of your assets and debts.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: OnePlan Apps Ltd
your_link: https://oneplan.app
your_city: London
email_address: hello@oneplan.app
facebook_username:
instagram_username: wealthwise.app
twitter_username: wealthwiseapp
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Net Worth
    description: With Wealth Wise, you can track your assets and debts in a single place.
    fontawesome_icon_name: magic

  - title: Watch your Net Worth grow
    description: Use our analytics and charts to track your wealth trends.
    fontawesome_icon_name: chart-line

  - title: Control of your data
    description: Your data never leaves your phone. Take backups, and even export to CSV.
    fontawesome_icon_name: lock

  - title: Fully offline
    description: No internet connection is needed. No login, no giving up personal data and your information stays on your phone.
    fontawesome_icon_name: star

  - title: Easy Reminders
    description: You can set weekly or monthly reminders to keep your net worth on track.
    fontawesome_icon_name: stopwatch

  - title: Detailed history of changes
    description: You can add historical data entry on each account and track historical data on all accounts.
    fontawesome_icon_name: history

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: white # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#00A3FF"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#00A3FF"
feature_icons_background_color: "#F5F5F5"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
